"""
integrations/sheets.py - Google Sheets integration.

Reads pending suppliers from a Google Sheet and writes results back.

Setup:
  1. Create a Google Cloud project and enable the Sheets API
    2. Create a service account and download the JSON key
      3. Save it to credentials/google-service-account.json
        4. Share your Google Sheet with the service account email
          5. Set GOOGLE_SHEET_ID and GOOGLE_SERVICE_ACCOUNT_FILE in .env

          Sheet format (tab: "Suppliers"):
            Columns: supplier_name | country | website | category | status | email | phone | ...
              Rows with status="" or status="pending" will be processed.
              """

              from typing import List, Optional
              from loguru import logger

              from config import get_settings
              from schemas.supplier import SupplierInput, ProcessingResult

              settings = get_settings()

              # Column indices (0-based) — adjust if your sheet differs
              COL_SUPPLIER_NAME = 0
              COL_COUNTRY = 1
              COL_WEBSITE = 2
              COL_CATEGORY = 3
              COL_STATUS = 4
              COL_EMAIL = 5
              COL_PHONE = 6
              COL_ADDRESS = 7
              COL_CONTACTS_JSON = 8
              COL_NOTES = 9


              def _get_sheet_client():
                  """Return an authenticated gspread client."""
                      try:
                              import gspread
                                      from google.oauth2.service_account import Credentials

                                              scopes = [
                                                          "https://www.googleapis.com/auth/spreadsheets",
                                                                      "https://www.googleapis.com/auth/drive.readonly",
                                                                              ]
                                                                                      creds = Credentials.from_service_account_file(
                                                                                                  settings.google_service_account_file,
                                                                                                              scopes=scopes,
                                                                                                                      )
                                                                                                                              return gspread.authorize(creds)
                                                                                                                                  except ImportError:
                                                                                                                                          raise RuntimeError(
                                                                                                                                                      "Google Sheets dependencies not installed. "
                                                                                                                                                                  "Run: pip install gspread google-auth"
                                                                                                                                                                          )
                                                                                                                                                                          
                                                                                                                                                                          
                                                                                                                                                                          def read_pending_suppliers() -> List[SupplierInput]:
                                                                                                                                                                              """
                                                                                                                                                                                  Read rows from Google Sheets where status is empty or 'pending'.
                                                                                                                                                                                      Returns a list of SupplierInput objects.
                                                                                                                                                                                          """
                                                                                                                                                                                              client = _get_sheet_client()
                                                                                                                                                                                                  sheet = client.open_by_key(settings.google_sheet_id)
                                                                                                                                                                                                      worksheet = sheet.worksheet(settings.google_sheet_tab)
                                                                                                                                                                                                      
                                                                                                                                                                                                          all_rows = worksheet.get_all_values()
                                                                                                                                                                                                              if not all_rows:
                                                                                                                                                                                                                      return []
                                                                                                                                                                                                                      
                                                                                                                                                                                                                          # Skip header row
                                                                                                                                                                                                                              data_rows = all_rows[1:]
                                                                                                                                                                                                                              
                                                                                                                                                                                                                                  suppliers = []
                                                                                                                                                                                                                                      for row in data_rows:
                                                                                                                                                                                                                                              # Pad row to expected length
                                                                                                                                                                                                                                                      while len(row) < COL_STATUS + 1:
                                                                                                                                                                                                                                                                  row.append("")
                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                          status = row[COL_STATUS].strip().lower()
                                                                                                                                                                                                                                                                                  if status not in ("", "pending"):
                                                                                                                                                                                                                                                                                              continue
                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                      name = row[COL_SUPPLIER_NAME].strip() if len(row) > COL_SUPPLIER_NAME else ""
                                                                                                                                                                                                                                                                                                              if not name:
                                                                                                                                                                                                                                                                                                                          continue
                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                  suppliers.append(
                                                                                                                                                                                                                                                                                                                                              SupplierInput(
                                                                                                                                                                                                                                                                                                                                                              supplier_name=name,
                                                                                                                                                                                                                                                                                                                                                                              country=row[COL_COUNTRY].strip() if len(row) > COL_COUNTRY else "",
                                                                                                                                                                                                                                                                                                                                                                                              website_hint=row[COL_WEBSITE].strip() if len(row) > COL_WEBSITE else "",
                                                                                                                                                                                                                                                                                                                                                                                                              category=row[COL_CATEGORY].strip() if len(row) > COL_CATEGORY else "",
                                                                                                                                                                                                                                                                                                                                                                                                                          )
                                                                                                                                                                                                                                                                                                                                                                                                                                  )
                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                      logger.info(f"Read {len(suppliers)} pending suppliers from Google Sheets")
                                                                                                                                                                                                                                                                                                                                                                                                                                          return suppliers
                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                          def write_results_to_sheet(results: List[ProcessingResult]) -> None:
                                                                                                                                                                                                                                                                                                                                                                                                                                              """
                                                                                                                                                                                                                                                                                                                                                                                                                                                  Write processing results back to the Google Sheet.
                                                                                                                                                                                                                                                                                                                                                                                                                                                      Updates status, email, phone, address, contacts JSON, and notes.
                                                                                                                                                                                                                                                                                                                                                                                                                                                          """
                                                                                                                                                                                                                                                                                                                                                                                                                                                              import json as json_module
                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  client = _get_sheet_client()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      sheet = client.open_by_key(settings.google_sheet_id)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          worksheet = sheet.worksheet(settings.google_sheet_tab)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              all_rows = worksheet.get_all_values()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  if not all_rows:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          logger.warning("Sheet is empty, cannot write results")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  return
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      # Build a name -> row index map
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          name_to_row = {}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              for i, row in enumerate(all_rows[1:], start=2):  # 1-indexed, skip header
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      if row and row[COL_SUPPLIER_NAME].strip():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  name_to_row[row[COL_SUPPLIER_NAME].strip().lower()] = i
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      updates = []
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          for result in results:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  row_idx = name_to_row.get(result.supplier_name.lower())
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          if row_idx is None:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      logger.warning(f"Could not find row for: {result.supplier_name}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  continue
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          if result.data:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      d = result.data
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  contacts_json = json_module.dumps(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  [c.dict() for c in d.contacts], ensure_ascii=False
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          status = "done" if result.status == "success" else "partial"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      updates.extend([
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {"range": f"{_col_letter(COL_STATUS)}{row_idx}", "values": [[status]]},
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {"range": f"{_col_letter(COL_EMAIL)}{row_idx}", "values": [[d.general_email or ""]]},
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {"range": f"{_col_letter(COL_PHONE)}{row_idx}", "values": [[d.general_phone or ""]]},
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {"range": f"{_col_letter(COL_ADDRESS)}{row_idx}", "values": [[d.headquarters_address or ""]]},
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {"range": f"{_col_letter(COL_CONTACTS_JSON)}{row_idx}", "values": [[contacts_json]]},
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {"range": f"{_col_letter(COL_NOTES)}{row_idx}", "values": [[d.notes or ""]]},
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ])
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      updates.append({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      "range": f"{_col_letter(COL_STATUS)}{row_idx}",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      "values": [[f"error: {result.error or 'unknown'}"]],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      if updates:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              worksheet.batch_update(updates)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      logger.info(f"Updated {len(results)} rows in Google Sheets")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      def _col_letter(zero_based_index: int) -> str:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          """Convert a 0-based column index to a letter (A, B, C, ...)."""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return chr(ord("A") + zero_based_index)
